safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Joseph Dreamer's project"
description: "The Power of Network and Communication"
baseurl: ""
url: "http://sangsucki.github.io" # replace by your site's url
facebook_username: sangsucki
github_username: sangsucki # (your name)
linkedin_username : josephleess
accent: "#f7f7e6" # accent color for blog column

author: "Joseph"
email: "sangseok.lee@duke.edu"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
